### ISSUE TITLE
Break down each API endpoint to service objects

### ISSUE THREAD

**Issue by fear-the-reaper** [intelowlproject/go-intelowl#21] opened 2022-05-24 19:07 UTC
Separate the API endpoints to their specific resource and make a service object in separate files. Furthermore, provide optional struct parameters.

- [ ] Separate the endpoints into service objects.
- [ ] Add their optional structs.
- [ ] Integrate context into the methods.

**Comment by eshaan7** [comment] 2022-07-14 08:31
Duplicate of #16.

**Closed as not planned by eshaan7** 2022-07-14 08:31 UTC
Labels: GSoC
